RESUME_TRAIN = False
OUTPUT_PREVIEW = False


BEST_MODEL_NAME = 'models/best.h5'
LAST_MODEL_NAME = 'models/save.h5'

TILE_SIZE = 128
OUTPUT_SCALE = 16
QUEUE_MULT = 32
MAX_FACE_SIZE = 48
MIN_FACE_SIZE = 8

USE_ADAM_OPTIMIZER = False
LEARNING_RATE = 1e-2
MOMENTUM = 0.5
NESTEROV = True
BATCH_SIZE = 1024
STEPS_PER_EPOCH = 128

DATASET_PATH = r'c:\datasets\findface'
