RESUME_TRAIN = True
OUTPUT_PREVIEW = False


BEST_MODEL_NAME = 'best.h5'
LAST_MODEL_NAME = 'save.h5'

TILE_SIZE = 128
OUTPUT_SCALE = 16

USE_ADAM_OPTIMIZER = False
LEARNING_RATE = 1e-2
MOMENTUM = 0.5
NESTEROV = True
BATCH_SIZE = 512
STEPS_PER_EPOCH = 256

DATASET_PATH = r'c:\databases\findface'
